CREATE TABLE `DM_FactSales` (
    `SalesOrderNumber` INT NOT NULL,
    `SalesOrderLineNumber` INT NOT NULL,
    `CustomerID` INT,
    `ProductID` INT,
    `ShipToAddressID` INT,
    `BillToAddressID` INT,
    `ShipmentMethod` TEXT,
    `UnitPrice` DECIMAL,
    `Discount` DECIMAL,
    `OrderQuantity` INT,
    `OrderLineTotal` DECIMAL,
    `OrderLineProfit` DECIMAL,
    `TaxAmount` DECIMAL,
    `OrderLineFreightCost` DECIMAL,
    `OrderStatus` INT,
    `OrderDate` Date,
    `DueDate` Date,
    `ShipDate` Date,
    `IsLateShipment` INT,
    CONSTRAINT PK_FactSales PRIMARY KEY (`SalesOrderNumber`, `SalesOrderLineNumber`)
	CONSTRAINT FK_CustomerID_FactSales FOREIGN KEY (`CustomerID`) REFERENCES Customer(`CustomerID`),
	CONSTRAINT FK_ProductID_FactSales FOREIGN KEY (`ProductID`) REFERENCES Product(`ProductID`),
	CONSTRAINT FK_ShipToAddressID_FactSales FOREIGN KEY (`ShipToAddressID`) REFERENCES Location(`AddressID`),
	CONSTRAINT FK_BillToAddressID_FactSales FOREIGN KEY (`BillToAddressID`) REFERENCES Location(`AddressID`),
	CONSTRAINT FK_OrderDate_FactSales FOREIGN KEY (`OrderDate`) REFERENCES Time(`Date`),
	CONSTRAINT FK_DueDate_FactSales FOREIGN KEY (`DueDate`) REFERENCES Time(`Date`),
	CONSTRAINT FK_ShipDate_FactSales FOREIGN KEY (`ShipDate`) REFERENCES Time(`Date`)
);
